In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel(r"D:\Customer A & R\data\raw\raw_large_user_data.xlsx")

In [3]:
data.head()

,Customer ID,Subscription Length (Months),Customer Satisfaction Score (1-10),Daily Watch Time (Hours),Engagement Rate (1-10),Device Used Most Often,Genre Preference,Region,Payment History (On-Time/Delayed),Subscription Plan,Churn Status (Yes/No),Support Queries Logged,Age,Monthly Income ($),Promotional Offers Used,Number of Profiles Created
0,C00001,12,10,4.85,4,Tablet,Action,Europe,On-Time,Basic,No,10,33,6250,5,2
1,C00002,12,8,1.75,9,Laptop,Thriller,Europe,On-Time,Basic,Yes,9,28,7018,1,5
2,C00003,3,4,2.75,9,Smart TV,Comedy,Asia,On-Time,Premium,Yes,3,18,1055,1,5
3,C00004,3,7,3.00,9,Smart TV,Drama,Europe,Delayed,Premium,No,5,32,6707,5,4
4,C00005,24,2,1.37,5,Mobile,Drama,North America,On-Time,Standard,Yes,2,59,1506,3,5

In [4]:
data.shape

(1000, 16)

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Customer ID                         1000 non-null   str
 1   Subscription Length (Months)        1000 non-null   int64
 2   Customer Satisfaction Score (1-10)  1000 non-null   int64
 3   Daily Watch Time (Hours)            1000 non-null   float64
 4   Engagement Rate (1-10)              1000 non-null   int64
 5   Device Used Most Often              1000 non-null   str
 6   Genre Preference                    1000 non-null   str
 7   Region                              1000 non-null   str
 8   Payment History (On-Time/Delayed)   1000 non-null   str
 9   Subscription Plan                   1000 non-null   str
 10  Churn Status (Yes/No)               1000 non-null   str
 11  Support Queries Logged              1000 non-null   int64
 12  Age                                 1000 non-null   int64
 13  Monthly Income ($)                  1000 non-null   int64
 14  Promotional Offers Used             1000 non-null   int64
 15  Number of Profiles Created          1000 non-null   int64
dtypes: float64(1), int64(8), str(7)
memory usage: 125.1 KB

In [6]:
data.columns

Index(['Customer ID', 'Subscription Length (Months)',
       'Customer Satisfaction Score (1-10)', 'Daily Watch Time (Hours)',
       'Engagement Rate (1-10)', 'Device Used Most Often', 'Genre Preference',
       'Region', 'Payment History (On-Time/Delayed)', 'Subscription Plan',
       'Churn Status (Yes/No)', 'Support Queries Logged', 'Age',
       'Monthly Income ($)', 'Promotional Offers Used',
       'Number of Profiles Created'],
      dtype='str')

In [7]:
list(data.columns)

['Customer ID',
 'Subscription Length (Months)',
 'Customer Satisfaction Score (1-10)',
 'Daily Watch Time (Hours)',
 'Engagement Rate (1-10)',
 'Device Used Most Often',
 'Genre Preference',
 'Region',
 'Payment History (On-Time/Delayed)',
 'Subscription Plan',
 'Churn Status (Yes/No)',
 'Support Queries Logged',
 'Age',
 'Monthly Income ($)',
 'Promotional Offers Used',
 'Number of Profiles Created']

In [8]:
data.describe()

,Subscription Length (Months),Customer Satisfaction Score (1-10),Daily Watch Time (Hours),Engagement Rate (1-10),Support Queries Logged,Age,Monthly Income ($),Promotional Offers Used,Number of Profiles Created
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,9.17700,5.379000,2.829420,5.511000,4.951000,43.840000,5251.452000,2.422000,2.937000
std,8.21859,2.856487,1.302673,2.871607,3.111636,15.356439,2720.859072,1.689607,1.430062
min,1.00000,1.000000,0.500000,1.000000,0.000000,18.000000,510.000000,0.000000,1.000000
25%,3.00000,3.000000,1.650000,3.000000,2.000000,30.000000,3073.250000,1.000000,2.000000
50%,6.00000,5.000000,2.890000,6.000000,5.000000,44.000000,5286.000000,2.000000,3.000000
75%,12.00000,8.000000,3.932500,8.000000,8.000000,57.000000,7598.250000,4.000000,4.000000
max,24.00000,10.000000,5.000000,10.000000,10.000000,70.000000,9994.000000,5.000000,5.000000

In [9]:
data.isnull().sum()

Customer ID                           0
Subscription Length (Months)          0
Customer Satisfaction Score (1-10)    0
Daily Watch Time (Hours)              0
Engagement Rate (1-10)                0
Device Used Most Often                0
Genre Preference                      0
Region                                0
Payment History (On-Time/Delayed)     0
Subscription Plan                     0
Churn Status (Yes/No)                 0
Support Queries Logged                0
Age                                   0
Monthly Income ($)                    0
Promotional Offers Used               0
Number of Profiles Created            0
dtype: int64

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
data.sample(5)

,Customer ID,Subscription Length (Months),Customer Satisfaction Score (1-10),Daily Watch Time (Hours),Engagement Rate (1-10),Device Used Most Often,Genre Preference,Region,Payment History (On-Time/Delayed),Subscription Plan,Churn Status (Yes/No),Support Queries Logged,Age,Monthly Income ($),Promotional Offers Used,Number of Profiles Created
138,C00139,3,2,0.98,8,Laptop,Drama,South America,On-Time,Basic,Yes,2,59,5318,3,2
915,C00916,12,2,2.02,2,Smart TV,Thriller,Africa,On-Time,Basic,Yes,1,51,8626,1,3
544,C00545,6,4,2.77,7,Tablet,Drama,Asia,Delayed,Basic,No,7,64,2088,5,5
346,C00347,1,8,4.52,8,Smart TV,Action,Asia,On-Time,Premium,No,10,54,1302,0,1
604,C00605,3,6,4.38,10,Laptop,Thriller,Asia,Delayed,Premium,Yes,6,42,1669,2,3

In [12]:
data["Churn Status (Yes/No)"].value_counts()

Churn Status (Yes/No)
Yes    539
No     461
Name: count, dtype: int64